### ISSUE TITLE
Thoughts on "when" api change

### ISSUE THREAD

**Issue by stephenh** [testpossessed/ts-substitute#1]
Hey, I came across your project by 1st finding the FluffySpoon library, having a few issues as well, and then googling for alternatives, i.e. checking the "ts-substitute" namespace, and hey you're here. :-)

I'm poking around a bit to see how different it is vs. FluffySpoon.

I'm curious about your thoughts, I'm wondering if the implementation of this concept would be simplified by adding an explicit `when` (or pick a better name) API that puts the substitute into "record" mode.

I.e. right now, whether a substitute is in record mode is a runtime decision about "have I been called before", i.e. for this test:

```typescript
    it('should be able to configure a return for a method call with literal values', () => {
        const expected = 'returned';
        const stringArg = 'something';
        const numberArg = 1;
        sub.stringMethod(stringArg, numberArg).returns(expected);
        sub.stringMethod(stringArg, numberArg).returns(expected);

        const result = sub.stringMethod(stringArg, numberArg);

        assert.equal(result, 'returned');
    });
```

I added the 2nd `sub.stringMethod...returns(...)` line, and it fails with `.returns is not a function` because the 2nd invocation of `sub.stringMethod` "just knows" that it should return the `expected` value now, instead of letting the user call `.returns`.

My thought is that this "runtime decision of record vs. replay" makes things a lot more complicated, because we have to then do the various mapped type gymnastics (that TS is admittedly great at) of having `stringMethod` return either the real string value || the additional `returns`/etc. methods.

It seems like just changing the API slightly to be:

```typescript
    it('should be able to configure a return for a method call with literal values', () => {
        const expected = 'returned';
        const stringArg = 'something';
        const numberArg = 1;
        when(sub).stringMethod(stringArg, numberArg).returns(expected);
        when(sub).stringMethod(stringArg, numberArg).returns(expected);

        const result = sub.stringMethod(stringArg, numberArg);

        assert.equal(result, 'returned');
    });
```

I.e. adding the notion of `when(sub).` returns a substitute that is _always_ in record mode, so the implementation is simpler, the mapped type is simpler, and (personally/biased) I think the mental model for end users is simpler.

Besides simpler impl, it also removes the problem of namespace overlap (i.e. if "returns" is a method the substituting-project actually uses) and also allows specifying how to handle multiple invocations (...although looks like there is also an `andDoes` floating around that is meant for this?)

I would be tempted to do the same thing with the assertions, i.e. `verify(sub).received().stringMethod(stringArg, numberArg)`.

So, dunno, I'm in somewhat of a torn "...should I try hacking together on my own 'simpler than fluffyspoon' mocking library" state, like I'd prefer to use something off the shelf, but I've hit a few sharp edges with fluffy and I haven't tried ts-substitute yet but ~kinda anticipate same-but-different sort of things, i.e. while the type system / APIs try to achieve this "it's ambiguous whether you're in record mode or replay mode" API.

And so just wanted to drop a random issue and wonder, wdyt of this proposed "add an explicit `when` api call / record mode"? Is it something you'd consider working into ts-substitute as an admittedly large breaking API change but (biased/imo) easier/simpler long-term impl? Would like to collaborate on that, or not really interested at this point?

**Comment by stephenh** [comment]
Granted, the `when` thing is very close to `ts-mockito`, but for reasons I can't quite articulate, I still like the simplicity of this substitute-style API.

**Comment by testpossessed** [comment]
Hi Stephen,

My first thought is that adding this kind of change would violate one of my primary goals, which is to stay true to the NSubstitute interface that this library is modelled on.

What I would be more inclined to look at is recognising that returns is being called again and replacing the first configuration.

I particularly like the clean code that comes from working directly with the substitute without the need to explicitly put it into record or replay mode or pass some property of the substitute to consumers.  When working with .NET I prefer NSubstitute over Moq (which I used to prefer over all the other options) because of the clean code it promotes.  One of the reasons I didn’t just go with something else like ts-mockito or TypeMoq is because of the need to do the explicit mode switching or use a property of the fake.

I will try to look into supporting re-configuring a substitute this weekend.

Mike

**Comment by stephenh** [comment]
Cool, yeah, makes sense re staying true to the "there is no explicit mode" vision. Looking at the original NSubstitute API/docs, it looks like they do have ways of handling things like multiple return values/etc.

**Comment by testpossessed** [comment]
Ahh!! That sounds like the test you wrote was intended to set up the subsitute to return different values on each call rather than replace the existing return value with a new one is that correct?

In NSubstitute you can achieve the multiple values thing by passsing a  comma separated list of values, which it provides in sequence as the method is called.  Once it runs out of values it returns the last one if the method continues to be called.

I definitely think there is value in providing that functionality, but also if the substitute is called as shown in your example I think the behaviour should be to replace the existing configured return value.

**Comment by stephenh** [comment]
> return different values on each call rather than replace the existing return value

Right.

> I definitely think there is value in providing that functionality

Cool.

> also if the substitute is called as shown in your example I think the behaviour
> should be to replace the existing configured return value

I'm fairly ambivalent about that, now that I understand the behavior, 1st call == record, all other calls = replay.

**Comment by testpossessed** [comment]
All done and published to npm as @testpossessed/ts-substitute

You can now pass a sequence of values to the returns method and the substitute will move through the sequence on each call to the method.  Once it gets to the last value in the sequence it keeps returning that on subsequent access.

Give it a go and let me know what you think

**Comment by stephenh** [comment]
Hey, thanks for the change! I lost my time slice / itch to port our tests over to something like fluffyspoon or ts-substitute, but I'll give this another go when I get a chance.
